### ISSUE TITLE
大佬，能否把抓包部分由Proxy修改为VPNService?

### ISSUE THREAD

**Issue by zxh126** [huanglqweiwei/CapturePacket#1]
大佬，能否把抓包部分由Proxy修改为VPNService?
可参考这个项目：https://github.com/huolizhuminh/NetWorkPacketCapture

**Comment by huanglqweiwei** [comment]
利用VPN抓包的项目已经有几个了的，除了你说的那个，还有：https://github.com/MegatronKing/NetBare
可以参考下。

**Comment by huanglqweiwei** [comment]
> 大佬，能否把抓包部分由Proxy修改为VPNService?
> 可参考这个项目：https://github.com/huolizhuminh/NetWorkPacketCapture

利用VPN抓包的项目已经有几个了的，除了你说的那个，还有：https://github.com/MegatronKing/NetBare
可以参考下。

**Comment by zxh126** [comment]
非常感谢，NetBare不错。
