### ISSUE TITLE
jniLib底层代码有吗？我看你源码上只有一个平台，方便上传一下源码

### ISSUE THREAD

**Issue by lycfr** [huanglqweiwei/CapturePacket#2]

**Comment by huanglqweiwei** [comment]
看下这个：https://github.com/jerboy/Tracepath
项目里面应该没有用到这个so，去掉试试

**Comment by huanglqweiwei** [comment]
> _No description provided._

看下这个：https://github.com/jerboy/Tracepath
项目里面好像没有用到这个so，去掉试试。
